### ISSUE TITLE
Any idea why nothing is shown?

### ISSUE THREAD

**Issue by kobigurk** [spectre1989/bitcoin_blockchain_visualiser#1]
I've looked at the blockchain listener code, it looks solid and the API doesn't seem to have changed.
Really interested in seeing this, but I'm unfortunately running linux at the moment so have limited capability to debug it. I will do it eventually, but thought you might have a quick explanation!

**Comment by spectre1989** [comment]
I'm not sure either, I'll have a poke around. Thanks for letting me know!

**Comment by kobigurk** [comment]
Found a hint in the unity log on linux: 

```
Not WebSocket connection response to the connection request.
```

**Comment by kobigurk** [comment]
Works on a clean build with Unity now with your new commits! :-)

**Comment by spectre1989** [comment]
Great! :)
